import type { Card, Expense } from '@/types/database';

/** 開発用モックデータ（Supabase未接続時に使用） */
export const MOCK_CARDS: Card[] = [
  {
    id: '1',
    user_id: 'mock-user',
    title: 'pokemon',
    display_name: null,
    name: 'リザードンex SAR',
    image_url: null,
    back_image_url: null,
    purchase_price: 5000,
    purchase_shipping: 500,
    grading_agency: 'PSA',
    grade: 10,
    grading_cost: 3700,
    cert_number: null,
    estimated_price: 20000,
    sold_price: null,
    sold_at: null,
    platform_fee: 0,
    quantity: 1,
    status: 'graded',
    memo: null,
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-15T00:00:00Z',
    ebay_linked: false,
  },
  {
    id: '2',
    user_id: 'mock-user',
    title: 'pokemon',
    display_name: null,
    name: 'ピカチュウAR',
    image_url: null,
    back_image_url: null,
    purchase_price: 800,
    purchase_shipping: 200,
    grading_agency: 'none',
    grade: null,
    grading_cost: 0,
    cert_number: null,
    estimated_price: 1200,
    sold_price: null,
    sold_at: null,
    platform_fee: 0,
    quantity: 1,
    status: 'raw',
    memo: null,
    created_at: '2026-03-10T00:00:00Z',
    updated_at: '2026-03-10T00:00:00Z',
    ebay_linked: false,
  },
  {
    id: '3',
    user_id: 'mock-user',
    title: 'yugioh',
    display_name: null,
    name: 'ブラック・マジシャン 初期',
    image_url: null,
    back_image_url: null,
    purchase_price: 15000,
    purchase_shipping: 800,
    grading_agency: 'BGS',
    grade: 9.5,
    grading_cost: 5000,
    cert_number: null,
    estimated_price: 45000,
    sold_price: null,
    sold_at: null,
    platform_fee: 0,
    quantity: 1,
    status: 'graded',
    memo: '美品',
    created_at: '2026-02-20T00:00:00Z',
    updated_at: '2026-03-20T00:00:00Z',
    ebay_linked: false,
  },
  {
    id: '4',
    user_id: 'mock-user',
    title: 'onepiece',
    display_name: null,
    name: 'ルフィ リーダーパラレル',
    image_url: null,
    back_image_url: null,
    purchase_price: 3000,
    purchase_shipping: 300,
    grading_agency: 'PSA',
    grade: 10,
    grading_cost: 3700,
    cert_number: null,
    estimated_price: 12000,
    sold_price: null,
    sold_at: null,
    platform_fee: 0,
    quantity: 1,
    status: 'graded',
    memo: null,
    created_at: '2026-03-05T00:00:00Z',
    updated_at: '2026-03-18T00:00:00Z',
    ebay_linked: false,
  },
  {
    id: '5',
    user_id: 'mock-user',
    title: 'pokemon',
    display_name: null,
    name: 'ミュウツーV SA',
    image_url: null,
    back_image_url: null,
    purchase_price: 8000,
    purchase_shipping: 500,
    grading_agency: 'PSA',
    grade: 9,
    grading_cost: 3700,
    cert_number: null,
    estimated_price: 15000,
    sold_price: 14500,
    sold_at: '2026-03-25T00:00:00Z',
    platform_fee: 1450,
    quantity: 1,
    status: 'sold',
    memo: 'メルカリで売却',
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-03-25T00:00:00Z',
    ebay_linked: false,
  },
];

export const MOCK_EXPENSES: Expense[] = [
  {
    id: '1',
    user_id: 'mock-user',
    card_id: null,
    category: 'grading',
    amount: 18500,
    description: 'PSA 5枚分',
    date: '2026-04-01',
    created_at: '2026-04-01T00:00:00Z',
  },
  {
    id: '2',
    user_id: 'mock-user',
    card_id: null,
    category: 'shipping',
    amount: 1200,
    description: 'メルカリ発送',
    date: '2026-03-28',
    created_at: '2026-03-28T00:00:00Z',
  },
  {
    id: '3',
    user_id: 'mock-user',
    card_id: null,
    category: 'packaging',
    amount: 2000,
    description: 'スリーブ・マグネットローダー',
    date: '2026-03-25',
    created_at: '2026-03-25T00:00:00Z',
  },
  {
    id: '4',
    user_id: 'mock-user',
    card_id: null,
    category: 'shipping',
    amount: 800,
    description: 'ヤフオク発送',
    date: '2026-03-20',
    created_at: '2026-03-20T00:00:00Z',
  },
];
